### ISSUE TITLE
Add bundled files to `.gitignore`

### ISSUE THREAD

**Issue by g-plane** [cherow/cherow#105]
Bundled files should not be commit into version control system, IMHO.

**Comment by KFlash** [comment]
@fkleuver Anything to say?

**Comment by fkleuver** [comment]
I don't believe this is a black-and-white rule that applies in all cases. There are valid reasons to commit build outputs:

- Makes it easier for people just downloading the files from a specific release
- Enables use of rawgit in tools like plunkr or stackblitz
- Build outputs per release are deterministic and locked in place
- Enables use of git diff to see how the compiled outputs are affected by changes we make during development
- Easier for us to compare and keep an eye on the build output size

Reasons not to do it:
- Skews the graphs that show how many changes there were (small change can look like a huge one)
- Large messy git diffs (though this can be fixed with `.gitattributes` settings to ignore those diffs)
- Makes it tempting for contributors to perform fixes in build outputs rather than in sources (we ought to manage this)

All that said, I think committing build outputs should be strictly limited to when we're doing a release. And those commits should contain *only* the build outputs, and nothing else. Those are the "release commits". This is a rule we're not currently applying and we should.

For the rest, I believe the pros outweigh the cons in our case but I'm open for discussion of course.

**Comment by g-plane** [comment]
You're right. There are some real-world projects which commits build files, such as the Vue.js repo. However, they only commit those files when publish new version, as what you said.

**Comment by fkleuver** [comment]
@KFlash Let's completely stop committing build outputs unless it's for a release followed directly by a publish. Example:

- The last work is done, commit those changes as you normally would (without building) -> working directory is clean
- Bump the version in package.json, build the project, commit package.json + dist folders with commit message "chore(all): prepare release 1.x.x"
- Npm publish

Under no other circumstances (and with no other changes committed) should the dist folders ever be committed. This is the only way to keep it clean and reviewable.

**Comment by Aladdin-ADD** [comment]
vue has put the `dist/*.js` in `.gitignore`. thought I'm not sure how it been added it to git repo --might be something like `git add dist -f`.

https://github.com/vuejs/vue/blob/dev/.gitignore#L13

**Comment by fkleuver** [comment]
Closing in favor of #133
