### ISSUE TITLE
Remove "cherow-linter" from this repo

### ISSUE THREAD

**Issue by g-plane** [cherow/cherow#120]
As we know, ESLint is mature and it has full eco-system. And Rome was not built in a day, so it's hard to build a full-featured module like ESLint. Also, we have `cherow-eslint` now, though it is still in progress and experimental.

Let me know your opinions if you disagree.

**Comment by fkleuver** [comment]
Yes, it's not that we necessarily want to reinvent the wheel everywhere. `cherow-linter` was created here to set the basic structure and to make it easy to get started in case any of us got struck with a good idea.

At that point we didn't know yet whether it would be possible to integrate with an existing linter and use cherow as the underlying parser instead. We simply hadn't investigated that yet. But that is the preferred method for reasons you mentioned, so I'm completely fine with renaming `cherow-linter` to `cherow-eslint`.

I'd prefer if we keep all derived products in the `packages` folder under this monorepo. It's understandable if you want to fidget around a little bit with a separate repo because the workflow is simpler then, but having a single repository has some important benefits that I think are crucial to Cherow's success on the long term:
- The stars won't be scattered over multiple repos
- A standardized, reusable workflow for each product
- One repository to clone, one repository to keep an eye on

So while I don't have any problems with you playing around in a separate repo for the time being, eventually the linter should end up in here (as `cherow-eslint` then, if you will) and that separate repo deleted - not the other way around.

**Comment by g-plane** [comment]
However there is no need to add everything to this repo, which will make the repo messy, though we are using lerna. Also, Babel is using lerna and monorepo as well, but their `babel-eslint` is still in a separated repo.

**Comment by fkleuver** [comment]
Based on what rules / logic would you then determine whether something belongs here in the monorepo, or in a separate repo?

**Comment by Aladdin-ADD** [comment]
For consistency, I am 👍 to in the monorepo.

**Comment by g-plane** [comment]
So should I move it to this repo?

**Comment by fkleuver** [comment]
Preferably, yes. Let me know if you run into any issues with that or need any help.
