### ISSUE TITLE
CI not running in PR, and no tests on 2.0 branch

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#123]
- The CI stopped working in PR's.  

- Tests doesn't run on 2.0 branch (*they pass locale*)

- Travis CI doesn't run on 2.0 branch

@fkleuver Any ideas?

**Comment by g-plane** [comment]
We can remove following:

https://github.com/cherow/cherow/blob/master/appveyor.yml#L9-L11

https://github.com/cherow/cherow/blob/master/.travis.yml#L14-L16

**Comment by KFlash** [comment]
@g-plane Remove?

Nothing wrong with the tests itself, it is a workflow issue again.

![locale](https://user-images.githubusercontent.com/31855118/41348746-35faa478-6f40-11e8-89b5-a94d1e8314d8.png)

**Comment by g-plane** [comment]
I mean, the settings of Travis CI and AppVeyor limit that tests can only be ran on master branch, except other branches.

**Comment by KFlash** [comment]
Once again 2.0 branch failed. Just for the record. The tests doesn't fail on my computer

![again](https://user-images.githubusercontent.com/31855118/41351977-a3530c2c-6f4a-11e8-9342-2e38c8ca9edb.png)

The image shows all latest tests pass without any issues.

**Comment by g-plane** [comment]
Possible reproduction steps:
- Run `rm -rf ./packages/cherow/node_modules`
- Run `yarn` and `lerna bootstrap`
- Run `lerna run test --scope=cherow`

However I found running below commands can work:
- Rename `cherow` to any other name in `packages/cherow/package.json` (I know it's impossible to do it in actual.)
- Run `yarn`
- Run `lerna run test --scope=cherow` (This may work.)

**Comment by KFlash** [comment]
@fkleuver Ideas?

**Comment by KFlash** [comment]
Closing. Seems like the workflow gets an allergic reaction when version number changes. Rolled back, and now it works fine.

**Comment by fkleuver** [comment]
@KFlash Let's not jump to conclusions here, if you look at those CI files you can see that it only runs the tests on the master branch. I did that for a good reason - the master branch is where we develop. Bleeding/next could be added, but I didn't add them before because they only kept breaking and there was no stability.

When you publish a new version, you also create a new git tag for that version to lock it in place and then you continue work on master branch (or bleeding, whatever).

If you need a new major branch to work on besides master, then the CI files need to be adjusted. Or you need to communicate to me what your plan is so I can put the CI in place to accomodate for it.

In any case, creating a branch for a version is not the right way to do this.

**Comment by Aladdin-ADD** [comment]
agreed! when developing a new major version(e.g. 2.0), mostly we cut a new branch named `1.x`, but new features will be landed on master.
![image](https://user-images.githubusercontent.com/13050025/41359498-3398cd82-6f5d-11e8-9175-92c8d30a90e4.png)
