### ISSUE TITLE
Broken watch task for tests

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#145]
The latest changes to the workflow have broken the `test:watch`

This is what I get

```js
Warning: Could not find any test files matching pattern: test/**/*.ts --watch
No test files found
```

**Comment by fkleuver** [comment]
Fixed by https://github.com/cherow/cherow/commit/90231fde864c978ca2faaa799f1276fe0e98a7ca

**Comment by g-plane** [comment]
@fkleuver Why add those packages again?

**Comment by fkleuver** [comment]
I didn't review the PR properly as I was too busy, so I didn't test it locally. Otherwise I would have caught this beforehand.
But those devDependencies need to stay, otherwise tools can't be run from within the package folder. Looping tasks (like `test:watch`) don't work properly via lerna so they must be run from within the package folder. And it's generally more convenient if you're only developing that package.
There's no harm in having those dependencies in local package folder. `lerna bootstrap` will hoist them. That's kind of the point :)

**Comment by g-plane** [comment]
Ok, I see.
