### ISSUE TITLE
Clarify some parser options

### ISSUE THREAD

**Issue by futagoza** [cherow/cherow#246]
I was just adding the parser to my project, and setting the options, but came across some that I wasn't sure about. Can you please clarify the following:

- *loc* - are lines and columns calculated regardless of this option?
- *skipShebang* - what does the parser do if this is false? (e.g. does it return AST with raw string?)
- *node* - what do you mean 'bypass scoping when run in a NodejS environment'?

**Comment by KFlash** [comment]
*loc* will only set location on each last node if set. Its calculated in lexer always due to performance reasons. But works the same as in other parsers.

*skipShebang* only skip the hash on first line. Think Unix console and comments. Esprima doesn't do this but acorn does similar for comments

*node* isn't done yet. It will in future let you use the native regex validator in browsers and nodeJS if set instead of cherows own. Same with block scoping and lexical bindings. This is a TODO for now

**Comment by futagoza** [comment]
lol thanks for the explanation, but I know what a shebang is 🤣 was curious if cherow returns something otherwise it looks like I'm going to have to implement this in my project as I need to know if there's a shebang within the given source as well as it's raw string.

As for the _node_ option, I would suggest you do one of the following:

- update the description for the option (currently seems to imply that it skips _something_, not _what_)
- just remove it from the readme, and within the source update it's comment and/or add a _TODO_ to it
- obliterate. I mean, this is a parser right? Leave the validation to other tools (e.g. ESLint)

**Comment by KFlash** [comment]
Raw string is possible through options. It will add a raw property on the
ast node.

I will consider it all soon as I'm back
