### ISSUE TITLE
Using cherow with @babel/traverse

### ISSUE THREAD

**Issue by coderaiser** [cherow/cherow#273]
Hi, thank you for a great parser :), I'm working on tool that [finds and removes unused variables](https://github.com/coderaiser/putout) and I'm interested on using parsers different from `@babel/parser` because I need to keep source code as untouched as possible and use `recast` for this purpose, but it has problem with `@babel/parser` and `strict mode` (https://github.com/benjamn/recast/issues/558) I have a [workaround for this](https://github.com/coderaiser/putout/blob/v2.17.2/lib/putout.js#L69-L74) but better to not have such things 🙂.

I see that your parser really fast and `estree` standard compatible, and want to use it, but I have problem with destructuring arguments like this: `const t = ({a}) => a`.
The thing is I'm using `@babel/traverse` and it is works good with `cherow` but It can't find variable declared this way.

To make things work I changed all `Property` to `ObjectProperty`, because `@babel/traverse` doesn't understand `Property` types (https://github.com/babel/babel/issues/9251).

**Code**

```js
const babel = require('@babel/parser');
const cherow = require('cherow');
const recast = require('recast');

const traverse = require('@babel/traverse').default;

const source = `
    const t = ({a}) => a
`;

const babelAST = babel.parse(source);
const cherowAST = recast.parse(source, {
    parser: {
        parse: cherow.parse,
    }
});

// fix for babel traverse it doesn't know about standard Property
traverse(cherowAST, {
    Property(path) {
        path.node.type = 'ObjectPattern';
    }
});

traverse(cherowAST, {
    Identifier(path) {
        console.log('cherow:', path.scope.hasBinding('a'));
        // outputs
        false
    }
});

traverse(babelAST, {
    Identifier(path) {
        console.log('babel:', path.scope.hasBinding('a'));
        //outputs
        true
    }
});
```

Could you please help me to understand why `path.scope` has binding in case of `@babel/parser` and hasn't binding in case of `cherow`? As I see `AST`-nodes almost the same, everything should work in the same way, and it is works for [most of my tests](https://github.com/coderaiser/putout/blob/v2.17.2/test/get-vars.js) but a couple related to destructuring of arguments. Interesting that `espree` works in the same way as `cherow`.

**Expected behavior:**
`path.scope` should have binding of a variable when destructuring arguments used

**Actual behavior:**
`path.scope` has no binding of a variable when destructuring arguments used

Could you please help me to get variable bindings working 🙂?

**Comment by KFlash** [comment]
cc / @fkleuver Could you take over this one?

**Comment by fkleuver** [comment]
@coderaiser Thanks for describing the issue in detail and providing a code sample. You are on point about Babel not knowing about `Property`.

Two issues with this code:
```ts
traverse(cherowAST, {
    Property(path) {
        path.node.type = 'ObjectPattern';
    }
});
```

- Because `@babel/traverse` doesn't know about `Property`, it will never enter that method and thus the rename doesn't happen
- You would need to rename it to `ObjectProperty`, not `ObjectPattern`

Cherow is actually following the ESTree standard as you can see [here](https://github.com/estree/estree/blob/master/es2015.md#objectpattern)

In fact there is no mention of `ObjectProperty` in either the ESTree spec of the ECMAScript spec itself, so I'm not sure what is babel's reasoning for deviating from this standard. Did you raise the issue to them as well?

I don't want to just send you away based on this notion, we're ready to co-operate and make things interoperate nicely. But in this case I think it's in everyone's best interest if `@babel/traverse` at least recognizes properties as they are defined in the ESTree spec, because there are more parsers following that.

**Comment by fkleuver** [comment]
> Did you raise the issue to them as well?

I just noticed that you already did. Okay, so I believe babel is at least aware of `Property` already as I've spotted several mappings from/to `ObjectProperty` in their code. Their babylon parser supports ESTree output which also supports this.

Which leads me to wonder: does the same problem/limitation occur if you tell babylon to parse as ESTree?

Also, have you seen this code? https://github.com/babel/babel/blob/master/packages/babel-traverse/src/visitors.js#L13
There must be some option somewhere. It's just that when I ran your code sample and manually inspected the visitor, it didn't have `Property` in its internal map. So you need to toggle something somewhere.

**Comment by coderaiser** [comment]
@fkleuver, thank you for a quick response, about `ObjectPattern` it was a typo, correct code should be with `ObjectProperty`

> Because @babel/traverse doesn't know about Property, it will never enter that method and thus the rename doesn't happen

You right, I fix it in a code bellow.

> Which leads me to wonder: does the same problem/limitation occur if you tell babylon to parse as ESTree?

Yes, when `estree` plugin used, traverse doesn't define variables also, looks like it is totally a problem with `@babel/traverse`, I send a [pull request](https://github.com/babel/babel/pull/9253) which is fixes this situation partially.

```js
const babel = require('@babel/parser');
const cherow = require('cherow');
const recast = require('recast');

const traverse = require('@babel/traverse').default;

const source = `
    const t = ({a}) => a
`;

const babelAST = babel.parse(source, {
    plugins: [
       'estree', // with estree plugin @babel/traverse also doesn't define variables
    ]
});
const cherowAST = recast.parse(source, {
    parser: {
        parse: cherow.parse,
    }
});

// fix for babel traverse it doesn't know about standard Property
traverse(cherowAST, {
    enter(path) {
        if (path.type !== 'Property');
            return;

        path.node.type = 'ObjectProperty';
    }
});

traverse(cherowAST, {
    Identifier(path) {
        console.log('cherow:', path.scope.hasBinding('a'));
        // outputs
        false
    }
});

traverse(babelAST, {
    Identifier(path) {
        console.log('babel:', path.scope.hasBinding('a'));
        //outputs
        true
    }
});
```

**Comment by fkleuver** [comment]
Hmm

> Babel doesn't aim to be compatible with ESTree (Babel's ast is a fork of it). In order to use other parsers, you should somethow convert their output to repect Babel's ast format.

That's an interesting thing to say when ESTree is a core feature in their own repo. But you already pointed that out.

@KFlash I kind of understand babel's stance because of the sheer size of their repo and existing ecosystem. To support non-babel stuff could exponentially increase their maintenance burden. 

However lack of interoperability with an ecosystem like that of babel could likewise be a big reason *not* to use cherow. I think we should try to be interoperable with babel and other stuff as a means to increase cherow adoption rate. It opens up a very large plugin eco system to be usable with cherow, for free. It may also pressure other parsers to try and be standards-compliant, ultimately making the ecosystem as a whole more coherent and thereby everyone's lives easier.

Cherow being standards-compliant doesn't mean it cannot interoperate with other parsers that are not compliant. All you need is a standards-compliant traverse library to convert from ESTree to babel format.

@coderaiser Maybe try either of these (or something else entirely if you find something better)?
https://github.com/Rich-Harris/estree-walker
https://github.com/estools/estraverse

When cherow 2.0 is done, we might go back to a monorepo structure again depending on the demand for various plugins. If we do go there, we can probably have a `@cherow/traverse` either written from scratch or using one of the existing libraries out there. Again, it all depends on the need. I think being standards-compliant lessens the need for a lot of custom work though :)

**Comment by coderaiser** [comment]
> Cherow being standards-compliant doesn't mean it cannot interoperate with other parsers that are not compliant. All you need is a standards-compliant traverse library to convert from ESTree to babel format.

I totally agree with you :), I think this can be a good start: [estree-to-babel](https://github.com/coderaiser/estree-to-babel), it fixes cases we talked about, and new cases can go there to. Thank you for detailed explanation and support :).

**Comment by fkleuver** [comment]
Excellent, thanks for taking that initiative :) Feel free to reach out in the future if you need help.

I think a reference to your new plugin would be a good addition to our docs as I am sure there are more people who need this kind of interoperability. Agree @KFlash ?

**Comment by KFlash** [comment]
@fkleuver We may support alternative AST output in the future - something I was thinking of for 2..2. That will fix this issue? Btw. Can you look at the alternative lexer code?
