### ISSUE TITLE
Question regarding plans for 2.0

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#276]
I'm in the process of prototyping some analysis-related functionality over a limited subset of the ES2019 specification and was wondering what you're planning to have cherow 2.0 be capable of beyond simply producing an ESTree AST. I ask because in the issues list I keep seeing references to "scoping" and so forth, and, having only the current release (1.6.x) to compare to, I'm finding myself wondering if anything I'm implementing might be redundant. When you guys refer to "scoping", are you talking about exposing metadata with respect to when and where the different lexical bindings in the AST actually become available? Is there anything else coming in 2.0 that is designed to facilitate analysis-related tasks beyond production of the core AST itself?

Just trying to stay informed so I don't waste time implementing stuff you guys are already doing. Keep up the good work, in any case! :)

**Comment by KFlash** [comment]
Hi. The main focus with 2.0 is to stay true to the ECMA specs, and in the specs you see things like block scoping and lexical bindings. Therefor the word "scoping". In comparison with Acorn - wich have only implemented lexical bindings and lexical scope - things like `function foo(bar, zoo) { let bar; }` will throw an error. And also block scoping where `{ function a() {} function a() {}} ` will throw an error. This is why "scoping" is mentioned.  

Also in v. 2.0 this kind of things will be throw an error `export {a};` because the exported binding are not declared. This is valid `export {a}; var a = 1;`

That's the biggest thing that now will land in Cherow 2.0 together with `onToken` for tokenization.

If you have any suggestions for other things you want to see implemented, just let me know and I will see what I can do.

**Comment by axefrog** [comment]
Thanks for the fast response! My primary needs revolve around analysis-based inference and transformation of source code. Unlike something like TypeScript, I'm prototyping some experimental ideas surrounding the possible state of different code points based on all the possible ways a given code point might be reached, which ones are redundant, the way different values can possibly change over time, discrete and fuzzy pattern-matching for the purposes of transformation and code generation, and so forth. I guess the outcome is kind of a hybrid of a static analyser, a code generator and a limited pseudo-VM implementation.

I can't think of what I'd suggest that wouldn't push things way out of scope for you. Knowing that the parser will perform duplicate declaration checking and the like is pretty handy though.

**Comment by KFlash** [comment]
So issue solved? 
By the way. I already have Cherow 2.0 working locale where everyting is implemented already, so I'm re-inventing the wheel atm to fix a few performance bottle necks.
