### ISSUE TITLE
migrating to cherow v2.0.0

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#284]
this is to track the changes in cherow v2.0.0:

+ new options have been introduced.
+ some bugfixes

**Comment by KFlash** [comment]
@aladdin-add You should also add that the AST output for arrows and functions is true to the ESTree specs now and not compatible with others parsers.

**Comment by g-plane** [comment]
Do we need a documentation website?

**Comment by KFlash** [comment]
I guess so. Too much changes in 2.0

**Comment by KFlash** [comment]
@aladdin-add Can you somehow document this? Regarding location tracking. Cherow try to follow the standards, but for Template literals there is a **huge**difference between Acorn and Esprima. Try to parse this ``foo`` and compare the ranges for the `quasis`. Here Acorn start to count from `0`. Esprima starts to count from `1|. After manually countring Cherow ended up with the same location data as in Esprima.
So this is the only time where Cherow differ from Acorns location tracking. Else we output the same and the same AST node position.

@fkleuver Why do you think it's like this? Done "by design" by Acorn?

**Comment by KFlash** [comment]
@aladdin-add Waiting for the documentation

**Comment by aladdin-add** [comment]
sorry to be late,  getting busy on some rl. stuff.

 I'll try to start it later in this weekend, but please feel free to take it if you have time. :(

**Comment by KFlash** [comment]
@aladdin-add I understand your situation. I'm in airport now waiting for a airplane to take me to the Netherlands so I can't do much on Cherow the next days. But when and if you do the documentation. You can also play around with the online demo to test things.

**Comment by aladdin-add** [comment]
@KFlash just made a summary.╮(╯▽╰)╭  I'm afraid I don't have much time to complete it --  on vocation. 
you give a hand? 🖐🖐
