### ISSUE TITLE
Possible keyword tolerance issue with template literal parsing

### ISSUE THREAD

**Issue by axefrog** [cherow/cherow#309]
**Code**

The keywords `await` and `async` seem like they should throw errors when used as template literal tokens in strict mode.

```js
// good:
cherow.parseScript('`${await}`'); // success
cherow.parseScript('`${async}`'); // success
cherow.parseScript('`${static}`'); // success
cherow.parseScript('`${static}`', { impliedStrict: true }); // error
cherow.parseScript('`${yield}`'); // success
cherow.parseScript('`${yield}`', { impliedStrict: true }); // error
cherow.parseScript('`${function}`'); // error

// bad:
cherow.parseScript('`${await}`', { impliedStrict: true }); // no errors
cherow.parseScript('`${async}`', { impliedStrict: true }); // no errors
```

As a side note, the error for using `yield` as a template token in strict mode is possibly less useful than it could be: `'undefined' may not be used as an identifier in this context`. I assume it's resulting from the fact that no argument follows the keyword, but it feels like the wrong error inside of a template literal.

**Comment by KFlash** [comment]
Thanks for finding this :) I need to mention that `await` and `async` is not completed yet due to the complexity with async arrows, so it will be fixed soon as I find a performant way of tracking this.  And it's all on my TODO.  

This is the current state according to the Test262 suite:

`✔ 163 invalid programs did not produce a parsing error (and allowed by the whitelist file)`

Regarding the error messages. You are right. That is something I need to fix in the end when I'm also going to test for error location. Most of the time now I'm using an universal `unexpected` and hope for the best :)

**Comment by axefrog** [comment]
Ah cool, got it. Not a bug then, just not done yet :)

**Comment by KFlash** [comment]
Yep, still work in progress. But I'm soon going to fix it.

`✔ 128 invalid programs did not produce a parsing error (and allowed by the whitelist file)`

**Comment by KFlash** [comment]
I have fixed most of this issues now as seen [here](https://github.com/cherow/cherow/blob/75ee827590f928cbf9840d50467e30ee824e51ef/test/parser/expressions/template.ts#L98).

**Comment by axefrog** [comment]
Cool. Out of curiosity, I notice you highlighted a line with the keyword `yield` in it, though that was a keyword I'd observed as working correctly already. Not sure if I'm just being dumb and missing what you're trying to point out :)

**Comment by KFlash** [comment]
You mentioned `yield`, so just pointed it out because the error was fixed. For `async` and `await` they are both seen as an identifier in this context  and shouldn't throw at all. Not in module code or strict mode. Sounds strange to me because this happens outside an async function, but can't find any tests related to it *and* no parsers throws on it. And in V8 you only get this message `await is not defined`, but if you adjust the code to this  `"use  strict"; var await = 123; `${await}`` it pass.
