### ISSUE TITLE
Support UTF-16 encoding

### ISSUE THREAD

**Issue by vlkosinov** [cherow/cherow#324]
It is not possible to parse code with non ASCII symbols as identifiers. 

**Code**

```js
cherow.parse('var название = 2')
```

**Expected behavior:**
Correctly parse input code

**Actual behavior:**
```js
cherow.cjs.js:405 Uncaught SyntaxError: Illegal character 'н' (1:4)
var название = 2
    ^
```

**Comment by fkleuver** [comment]
@KFlash Didn't we use to have a couple of thousand tests for all valid identifier chars?

**Comment by KFlash** [comment]
@fkleuver In v. 1.6x yes. Seems like a bug happened in the rewrite that isn't covered by any tests

**Comment by KFlash** [comment]
@fkleuver I'm releasing to public some of my private code now, and if you port my lexer code to work with Cherow 2.0 this issue should be solved. I'm soon done with the lexer code - found [here](https://github.com/cherow/cherow/tree/lexer_demo) and a test for this issue is seen [here](https://github.com/cherow/cherow/blob/lexer_demo/test/internal/scanner/identifiers.ts#L74). 

Should be easy enough to backport, but I have no time for that now.

**Comment by KFlash** [comment]
Closing as it seems that @fkleuver will not release Cherow 2.0 yet.

Meanwhile try the [meriyah parser](https://github.com/meriyah/meriyah) and I'm sure this issue is solved.
