### ISSUE TITLE
"use strict" directive

### ISSUE THREAD

**Issue by AugustinLF** [cherow/cherow#37]
Hi, amazing job with the parser, I'm playing a bit with it, and I struggle to understand how you parse the `"use strict"` directive. I compared the output of running cherow, babylon and the flow-parser against this program:
```javascript
"use strict";
```
Flow's output is equivalent to cherow's one, but annotates the `ExpressionStatement` with the property `directive: "use strict"`, which is something you can find in the [estree spec](https://github.com/estree/estree/blob/1da8e603237144f44710360f8feb7a9977e905e0/es5.md#directive). Babylon works differently, putting the statement in a directive array (and not the body). On the other hand, cherow's AST does no such thing, there is no trace in the AST that this `ExpressionStatement` is a directive. Is it normal?

My guess would be that the correct output should be the same as flow-parser's. If you agree with me, I'd be happy to make a PR :)

**Comment by KFlash** [comment]
@AugustinLF Hi. Thanks for linking this :) It's not easy.  Regarding the strict directive. The ESTree specs was recently accepted, or at least a couple of weeks ago. At first I was not sure if I should implement this or not because of duplication of the `raw` and `directive` property on the node (*if you follow Esprima, Acorn and Babylon). But I had to go with the flow.

So to your questions. In current Master branch there doesn't exist such implementation, but if you look at the `next` branch you will find it half-way implemented. However. You have to use the `directives` option to enable it, and it only works for script code. And there exist a few bugs in current implmentation too.

Is this what you wanted?

Regarding PR. I would be happy if you want to help out fixing the strict directive implementation and current issue. In that case you can send a PR to the `Next` branch.

The next release of the parser will hopefully be released within a few days. It's a mayor improvements over the current one.

**Comment by KFlash** [comment]
@AugustinLF  The directive node option are mentioned [here](https://github.com/cherow/cherow/tree/next#options)

**Comment by KFlash** [comment]
@AugustinLF Do you  still want to handle the strict directive? I'm close now to release the new version. Maybe within one day. Need to validate things. BTW. Any knowledge about JSX Fragments?

**Comment by KFlash** [comment]
Closing this. If you still want to help, send a PR to Master branch.

**Comment by AugustinLF** [comment]
Hey, sorry for the late answer! I tested my needs (which are, adding cherow support to [prettier](https://github.com/prettier/prettier/)), and the new directive feature seems to work (I didn't do exhaustive tests), great \o/

Regarding JSX fragments, it depends on what you mean, I work wotk react, and know how they are supposed to behave, but I don't know what you'd need :)

**Comment by KFlash** [comment]
Hi

Ok. Regarding direvtives nodes. They are still not implemented for module
code. But glad it worked!

Jsx fragments. What i need? Well. Get it implemented into the parser. Do
you think you have time and can fix it?

**Comment by KFlash** [comment]
@AugustinLF Directives for module code will land in my next commit.
