### ISSUE TITLE
Unterminated regular expression literal

### ISSUE THREAD

**Issue by calebboyd** [cherow/cherow#92]
**Code**

```js
cherow.parseScript('"some string".replace(/=+$/, "");', { node: true });
```

**Expected behavior:**
It should not error in node.js
**Actual behavior:**
`Unterminated regular expression literal`

**Comment by KFlash** [comment]
That is an expected behavior, and it's related to NodeJS itself and isn't a Cherow bug.

I know there are plans to develop a regexp validator, but I'm not jumping into that code. 

As a temporary solution for your issue until the main developer is in place again, I have changed the behavior of `{ node: true}` so it will not validate any regular expressions if you use it. 

If this works for you, please close this issue.

/ J.K
