### ISSUE TITLE
Cherow's future

### ISSUE THREAD

**Issue by KFlash** [cherow/cherow#96]
Cherow was created because existing parsers were too slow, and none of these parsers would fare any chance against the official Test262 suite. 

The goal is reached, although Cherow is far from perfect. But it's time too move on...

During my work on Cherow I used various tools, and I found them all very slow, and they doesn't fit our needs. So in the future Cherow will still exist as it does today as a parser, but we will now focus on developing the packages listed below with the same performance as Cherow:

- [ ] TypeScript parsing

- [ ] Flow parsing

- [ ] Linter 

- [ ] Minifier

- [x] CLI

- [ ] Transpiler (*long term*)

- [ ] Module bundler  (*long term*)

**Comment by Aladdin-ADD** [comment]
Hi, to improve the perf of eslint, I was considering developing an esprima-compatible JavaScript parser on the top of Cherow, just like espree. Could you share your insights on this? Thanks! ❤️

**Comment by KFlash** [comment]
Gitter is a better place for this. You can ping me there

**Comment by aleclarson** [comment]
I'm very excited for `cherow-minify` in the (near?) future!

Also, I'm definitely considering using Cherow as the parser for [nebu](https://github.com/aleclarson/nebu). It should be easy, because both produce the same AST, correct?

I've made a request for [Bublé](https://github.com/Rich-Harris/buble) to adopt Cherow, too. (see [here](https://github.com/Rich-Harris/buble/issues/138))

**Comment by KFlash** [comment]
I'm out of town ATM, but regarding your questions. Cherow-minify will be done *after* I'm done with both Flow and TypeScript. And that will happen soon after I'm done with v. 2.0 of Cherow itself. 

I can't give any exact date. Sometimes I may run into issues that take longer time than expected to fix or my RL ask for some of my time. Something that has happened now. After my own schedule I'm 5 days delayed on completing v. 2.0 of the parser.

Cherow conforms to the ESTree specs, and there should be no differences between Cherow and Acorn as long as you avoid using the `next` option. That option enabled Stage 3 proposals and the AST for some of this features are "marked" as experimental in the ESTree repo. This is mostly related to class fields I guess.
I have not thought about the API for the minifier yet, but as a base it will use the same options as Cherow, but it will be extended with it's own options as well similiar to what you mentioned.

**Comment by aleclarson** [comment]
I'm curious how you plan to do the code generation for the minifier. 😄 Perhaps you should use [magic-string](https://github.com/Rich-Harris/magic-string), which does simple string splicing instead of generating the final string from scratch (after mutating the AST). It would save you time, but maybe you're more interested in rolling your own generator for speed's sake. Cheers!

**Comment by KFlash** [comment]
Performance is the most important thing with Cherow, and tbh. the main reason why I'm 5 days after my own schedule. Fixing a regex validator - and I guess over 300 different combos to find the perfect match. 
I worked on it now on my laptop, and suddenly it all "clicked" in place, and I can finish it and move on.

And the way I exposed the regex validator API is similar to what I'm going to do for tokenizing, comment attachment and other stuff.

**Comment by aleclarson** [comment]
Regarding the minifier's sourcemap generator, you should take a look at [metro-source-map](https://github.com/facebook/metro/tree/master/packages/metro-source-map). There's even [an article](https://medium.com/@david.aurelio/medium-fast-source-map-generation-for-react-native-ea5549007c18) detailing some of the optimizations made.

**Comment by KFlash** [comment]
I will look into it even more when I get there. ATM. I had to get [this code](https://github.com/cherow/cherow/blob/recovery/packages/cherow/src/lexer/regexp.ts) out of the door.

Now I'm going to fly back home!

**Comment by achun** [comment]
My written English is not good enough. The content is long, you need to take some time.

Avoid ambiguity caused by machine translation, I keep Chinese.
为了避免机器翻译引起的歧义, 我保留中文.

My purpose:
I want to introduce new methods to developers and get support to improve the overall ECMAScript source code ecology.

我的目的:
我想介绍新的方法给开发者, 并得到拥护, 提升整个 ECMAScript 源码生态.

cherow is brand new, this is an opportunity for me.
cherow 是全新的, 这对我是一个机会.

So,,, See https://esdiscuss.org/topic/proposal-static-type-constraints-features

I feel unable to get the support of tc39 members. Then, for convenience, I update the proposal in Chinese.
我感觉无法得到 tc39 成员的支持, 然后, 为了方便, 我用中文更新提案.

Because the `void typeExpression` has no side effects, I will still use it in reality.
因为 void 类型表达式是无副作用的, 我还是会在现实中使用它.

The proposal is actually a derivative of another project.
该提案其实是另一个项目的衍生品.

The cause is that I cannot tolerate the annotation style of `@param`
起因是我无法忍受 `@param` 这种注释风格.

I designed an annotation style that conforms to human reading habits. When watching the source code, the eyeball does not have to roll up or down.
我设计了一种符合人类阅读习惯的注释风格, 看源码时眼球无需上下翻滚.

E.g: cherow parser.ts

```js
/**
 * Creates the parser object
 *
 * @param source The source coode to parser
 * @param sourceFile Optional source file info to be attached in every node
 */
export function createParser(
    source: string,
    sourceFile: string | void,
): Parser {
    return {/*....*/}
}
```

The void typeExpression:

```js
export function createParser(
    source = void !'',   // source The source coode to parser
    sourceFile = void '' // sourceFile Optional source file info to be attached in every node
) {
    void Parser;  // Creates the parser object
    return {/*....*/}
}
```

The default document generated by this style is still the source code, but simply extract the source code associated with the type declaration.
这种风格生成的缺省文档依然是源代码, 只是简单提取和类型声明有关的源码.

And it is legal, at least at the grammatical level.
而且是合法的, 至少在语法层面.

Even depending on the position of the tail comment, you can keep all the source code in the document, like:
甚至依据尾注释的位置, 可以保留全部的源码到文档, 就像:

```js
export function parse(
    source = void !'',            // source source code to parse
    options = void Options // options parser options
) {
  void ESTree.Program;
  return options && options.module
    ? parseModule(source, options)
    : parseScript(source, options);
  // Parse either script code or module code
  // see [Link](https://tc39.github.io/ecma262/#sec-scripts)
  // see [Link](https://tc39.github.io/ecma262/#sec-modules)
}
```

Sometimes, writing a document is not as straightforward as looking at the source code, And it is borderless.
有时候, 写文档还不如直接看源代码更清晰, 而且是无国界的.

Maybe I'm lucky to get your support. Then please support the `void typeExpression` in cherow 2.0.
或许我很幸运, 能得到你的认同, 那就请在 cherow 2.0 中支持  `void typeExpression` 吧.

I have to say that until now, I haven’t got a staunch supporter.
不得不说, 到现在为止, 我还没得到一个坚定的支持者.

**Comment by g-plane** [comment]
I have published [`cherow-eslint`](https://github.com/g-plane/cherow-eslint) which is for ESLint, but it is experimental.

**Comment by KFlash** [comment]
Nice work @g-plane ! Btw. Do you have any deep knowledge about regex?

**Comment by g-plane** [comment]
Can you give an example?

**Comment by KFlash** [comment]
Can you ping me on gitter?

**Comment by g-plane** [comment]
@achun 请问您的想法是不是为了文档？

**Comment by g-plane** [comment]
@achun cherow 仅仅是一个解析器，它不会进行文档提取等类似的工作。如果你有写过 TypeScript 的话，可以使用 TypeDoc 等工具。或者，你也可以根据 cherow 生成的 AST 自己提取信息并生成文档。

**Comment by achun** [comment]
@g-plane 误解了, 我没有要求对文档有支持, 那个工作我已经开始.
我想要得到支持的是 void 类型表达式

**Comment by g-plane** [comment]
那对我的误解表示抱歉。

不过，像这种代码已经是合法的 JavaScript，所以没什么需要特别的支持吧？

```javascript
export function createParser(
    source = void !'',   // source The source coode to parser
    sourceFile = void '' // sourceFile Optional source file info to be attached in every node
) {
    void Parser;  // Creates the parser object
    return {/*....*/}
}
```

**Comment by achun** [comment]
哎呀, 很激动啊, 终于有人可观的提到这个 void 表达式的关键了.

**最终目标是要生成 类似 Flow 的 typeAnnotation 类型的, 这样才能进行 ESLint,
实现静态类型检查.**

要说与 Flow, TS 的不同, 最大的就是 这个合法了, 不需要 build 就能运行,
进行类型检查只是环节中的一项, 而且可以随时进行, 也可不进行, 也可以剔除 void 表达式, 类似 flow-strip-types. 不剔除也能正常工作.

**Comment by g-plane** [comment]
您的意思是基于这种语法进行类型检查？

**Comment by achun** [comment]
是的, 具体过程是这样:
为 void 类型表达式开发一个 cherow 插件, 功能和 Flow 的插件类似.
区别就是类型注解的形式和位置不同. 最终生成的都是 typeAnnotation 节点. 语义也一样.
当然有可能会产生新的类型, 也有可能 Flow 有的类型, void 类型表达式无法表达.

最新的版本在 https://gitlab.com/achun/proposal-static-type-constraints-features

**Comment by g-plane** [comment]
首先 cherow 只是一个解析器，不是编译器。它不会去完成类型检查工作。

其次，静态类型检查是个非常复杂的工作。看看 Flow 或 TypeScript 的源码就知道了。即使是 ESLint 中的 `valid-jsdoc` 规则也仅仅是检查您的 JSDoc 是否符合语法，而不会检查具体的类型是否匹配。

**Comment by aleclarson** [comment]
@achun @g-plane I feel this discussion should be in its own thread. As @g-plane said, there's nothing to be done in Cherow to support your syntax if it's already legal JavaScript.

**Comment by achun** [comment]
@g-plane 抱歉, 我有没有表达清楚, 类型检查肯定不是 cherow 要做的, 这样工作就和 ESLint 重复了, 
我是说, void 类型表达式和 flow 是一个级别的, 都是用来描述类型的,
希望能支持 void 类型表达式, 就像对 flow 的支持一样.
类型检查的问题有我来完成, 或者寻求社区的帮助完成.

**Comment by KFlash** [comment]
@aleclarson What about a chinese issue ticket? Can you fix it?

**Comment by g-plane** [comment]
@achun 不妨新建一个 issue 讨论？

**Comment by KFlash** [comment]
Just open a new issue in chinese. Or @g-plane and @achun what about moving this discussion to e.g gitter? And be aware only a few understand your language. English is the common one

**Comment by g-plane** [comment]
OK.

**Comment by KFlash** [comment]
I think this issue ticket contains too much chinese language so people will be confused. So I'm closing this now. It's also better to mention this in the docs somewhere rather than a issue ticket.
